### ISSUE TITLE
interproscan-5.26-65.0 fails in mobidb-lite.py

### ISSUE THREAD

**Issue by gabo-ing** [ebi-pf-team/interproscan#43] opened 2017-11-09 21:35 UTC
Hello:
I'm trying to run Interproscan-5.26-65.0 using a nucleotide fasta, but it fails at mobidb-lite step even with the test file. 

The command that causes this issue is: ./interproscan.sh -t n -i test_nt_seqs.fasta

Full error is: 

2017-11-09 18:26:37,137 [amqEmbeddedWorkerJmsContainer-10] [uk.ac.ebi.interpro.scan.management.model.implementations.RunBinaryStep:188] ERROR - Command line failed with exit code: 1
Command: python bin/mobidb/mobidb-lite.py -a 64 -t 1 -bin /media/gabo/ba45dce6-59ea-4965-834d-639da4d43d71/my_interproscan/interproscan-5.26-65.0/bin/mobidb/binx /media/gabo/ba45dce6-59ea-4965-834d-639da4d43d71/my_interproscan/interproscan-5.26-65.0/temp/precision_20171109_182423769_2hyh//jobMobiDBLite/000000000001_000000000073.fasta 
Error output from binary:
Traceback (most recent call last):
  File "bin/mobidb/mobidb-lite.py", line 455, in <module>
    out = run_mobidb(binDirectory, args.threads, args.longOutput, acc, seq, args.architecture, verbose = args.verbose)
  File "bin/mobidb/mobidb-lite.py", line 198, in run_mobidb
    if ele.get():
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
IndexError: list index out of range

I spoke to the guys developing mobidb and they told me that mobidb only accepts aminoacid sequences, so I guess something weird is going on in the translation step 

Has someone else found the same issue? currently I'm trying Interproscan with mobidb analysis disabled

Cheers,

Gabriel

**Comment by gsn7** [comment] 2017-11-16 16:04
We have run that command hundred of times and never got any problems with mobidb. 
Have you changed anything wrt translation of nucleotide sequnces, e.g., using a different program other than  bin/nucleotide/getorf?

**Comment by gabo-ing** [comment] 2017-11-16 19:47
Hi gsn7: 
Nothing was changed (this is a fresh installation of interproscan) and I'm running it with default parameters. From what I know, it should be using default binaries as well

Cheers,
Gabriel

**Comment by macarima** [comment] 2017-12-10 12:56
I also got this problem for several months. So I disabled mobidb-lite every time.
This is a serious problem.

**Comment by gsn7** [comment] 2017-12-11 12:27
a bit of debugging may help us see where the problem is coming from:
add the following line to bin/mobidb/mobidb-lite.py between line 200 and line 201
`print ('predictor: ' + str(ele2["pred"]))`
then run the following command and send us the output:
`python bin/mobidb/mobidb-lite.py -a 64 -t 1 -bin <interproscan_install_dir>/bin/mobidb/binx test_all_appl.fasta`

**Comment by sujaikumar** [comment] 2018-02-12 12:52
I have the same problem (mobidb lite fails)

@gsn7 I added the `print ('predictor: ' + str(ele2["pred"]))` line and got this:
```
python bin/mobidb/mobidb-lite.py -a 64 -t 1 -bin bin/mobidb/binx test_all_appl.fasta
Traceback (most recent call last):
  File "bin/mobidb/mobidb-lite.py", line 456, in <module>
    out = run_mobidb(binDirectory, args.threads, args.longOutput, acc, seq, args.architecture, verbose = args.verbose)
  File "bin/mobidb/mobidb-lite.py", line 169, in run_mobidb
    disbinFile, flatFile = generate_files(acc, seq)
  File "bin/mobidb/mobidb-lite.py", line 149, in generate_files
    f_disbin.write("1\n{0}\n{1}".format(len(seq),seq))
  File "/ceph/software/conda/lib/python3.6/tempfile.py", line 483, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'
```

@macarima do you have a way of disabling mobidb for all users (rather than just leaving it out from a `-appl` list?)

**Comment by sujaikumar** [comment] 2018-02-12 12:53
@gsn7 - I am using python3 - is that the problem? Don't want to change it right now (everything else works) so is there a quick fix for disabling mobidb for everyone? Do I just delete the binary?

**Comment by gsn7** [comment] 2018-02-13 16:40
@sujaikumar @macarima there is no quick way of disabling mobidb when its giving you errors. You will have to use the -appl option and specify the analyses you want
Can you send the example input where mobidb is failing so that we can test and feedback to the mobidb team? It looks like a bug in their code.

**Comment by macarima** [comment] 2018-02-13 16:54
@sujaikumar No. I used the -appl option without mobidb. It seems that there is no way to disable mobidb.

**Comment by dongjoban17** [comment] 2018-03-11 23:40
Still getting the same error (matching the error output that @sujaikumar posted) in 5.28-67.0.

**Comment by timkahlke** [comment] 2018-03-27 02:48
@sujaikumar Your problem is python3. It only runs with python 2.7.x I had the same error after installing miniconda and didn't realize that my python was sym-linked to python3. Changed it, problem solved.

**Comment by macarima** [comment] 2018-03-27 04:05
I'm using Python 2.7.
I still got problems failing in mobidblite.

2018년 3월 27일 (화) 오전 11:48, Tim Kahlke <notifications@github.com>님이 작성:

**Comment by gsn7** [comment] 2018-03-27 08:08
@macarima attach the file input on which mobidb is failing

**Comment by gsn7** [comment] 2018-06-26 15:31
this bug is now fixed in the latest release

**Closed** 2018-07-30 09:34 UTC
