### ISSUE TITLE
kvstore/proteinDB/****.sst (No such file or directory)

### ISSUE THREAD

**Issue by minhasbushra** [ebi-pf-team/interproscan#179] opened 2021-01-11 16:47 UTC
While running interproscan-5.48-83.0, I am continuously getting error as a file not found in proteinDB and the program crashes at ~94%. I have ran it a couple of times but still getting same problem every time. The test runs works fine with output. I tried with a smaller file and it ran successfully but with 5000 sequence file it is crashing. Any suggestions.??

Here is the error..

11/01/2021 03:34:48:972 94% completed
2021-01-11 04:09:10,554 [amqEmbeddedWorkerJmsContainer-1] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:213] ERROR - Execution thrown when attempting to executeInTransaction the StepExecution.  All database activ
ity rolled back.
java.lang.RuntimeException: Could not open table 577
        at org.iq80.leveldb.impl.TableCache.getTable(TableCache.java:99) ~[leveldb-0.12.jar:0.12]
        at org.iq80.leveldb.impl.TableCache.newIterator(TableCache.java:80) ~[leveldb-0.12.jar:0.12]
        at org.iq80.leveldb.impl.TableCache.newIterator(TableCache.java:75) ~[leveldb-0.12.jar:0.12]
        at org.iq80.leveldb.impl.Level0.get(Level0.java:100) ~[leveldb-0.12.jar:0.12]
        at org.iq80.leveldb.impl.Version.get(Version.java:169) ~[leveldb-0.12.jar:0.12]
        at org.iq80.leveldb.impl.VersionSet.get(VersionSet.java:223) ~[leveldb-0.12.jar:0.12]
        at org.iq80.leveldb.impl.DbImpl.get(DbImpl.java:616) ~[leveldb-0.12.jar:0.12]
        at org.iq80.leveldb.impl.DbImpl.get(DbImpl.java:577) ~[leveldb-0.12.jar:0.12]
        at uk.ac.ebi.interpro.scan.persistence.kvstore.LevelDBStore.get(LevelDBStore.java:109) ~[interproscan-persistence-5.48-83.0.jar:?]
        at uk.ac.ebi.interpro.scan.persistence.ProteinDAOImpl.getProtein(ProteinDAOImpl.java:150) ~[interproscan-persistence-5.48-83.0.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor140.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at com.sun.proxy.$Proxy77.getProtein(Unknown Source) ~[?:?]
        at uk.ac.ebi.interpro.scan.management.model.implementations.PrepareForOutputStep.simulateMarshalling(PrepareForOutputStep.java:279) ~[interproscan-management-5.48-83.0.jar:?]
        at uk.ac.ebi.interpro.scan.management.model.implementations.PrepareForOutputStep.execute(PrepareForOutputStep.java:100) ~[interproscan-management-5.48-83.0.jar:?]
        at uk.ac.ebi.interpro.scan.jms.activemq.StepExecutionTransactionImpl.executeInTransaction(StepExecutionTransactionImpl.java:87) ~[interproscan-5.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor114.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at com.sun.proxy.$Proxy141.executeInTransaction(Unknown Source) ~[?:?]
        at uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener.onMessage(LocalJobQueueListener.java:197) [interproscan-5.jar:?]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:761) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:699) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076) [spring-jms-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.io.FileNotFoundException: /home/****/project-aces/test/temp/***_20210110_223340333_k3os/kvstore/proteinDB/000577.sst (No such file or directory)
        at java.io.FileInputStream.open0(Native Method) ~[?:?]
        at java.io.FileInputStream.open(FileInputStream.java:219) ~[?:?]
        at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
        at org.iq80.leveldb.impl.TableCache$TableAndFile.<init>(TableCache.java:126) ~[leveldb-0.12.jar:0.12]
        at org.iq80.leveldb.impl.TableCache$TableAndFile.<init>(TableCache.java:115) ~[leveldb-0.12.jar:0.12]
        at org.iq80.leveldb.impl.TableCache$1.load(TableCache.java:68) ~[leveldb-0.12.jar:0.12]
        at org.iq80.leveldb.impl.TableCache$1.load(TableCache.java:63) ~[leveldb-0.12.jar:0.12]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[guava-27.1-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[guava-27.1-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155) ~[guava-27.1-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[guava-27.1-jre.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3953) ~[guava-27.1-jre.jar:?]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3976) ~[guava-27.1-jre.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4960) ~[guava-27.1-jre.jar:?]
        at org.iq80.leveldb.impl.TableCache.getTable(TableCache.java:92) ~[leveldb-0.12.jar:0.12]
        ... 44 more

2021-01-11 04:09:10,649 [amqEmbeddedWorkerJmsContainer-1] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:218] ERROR - 2. The exception is :java.lang.RuntimeException: Could not open table 577
2021-01-11 04:09:10,649 [amqEmbeddedWorkerJmsContainer-1] [uk.ac.ebi.interpro.scan.jms.worker.LocalJobQueueListener:219] ERROR - StepExecution with errors - stepName: stepPrepareForOutput
2021-01-11 04:09:10,951 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:25] FATAL - Analysis step 10 : Prepare proteins for output of the completed analysis for proteins 1 to 1000 has failed irretrievably.  Available StackTraces follow.
2021-01-11 04:09:10,956 [main] [uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError:42] FATAL - The JVM will now exit with a non-zero exit status.
2021-01-11 04:09:10,956 [main] [uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster:332] ERROR - Exception thrown by StandaloneBlackBoxMaster: 
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
        at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:43) ~[interproscan-5.jar:?]
        at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:157) [interproscan-5.jar:?]
        at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:475) [interproscan-5.jar:?]
java.lang.IllegalStateException: InterProScan exiting with non-zero status, see logs for further information.
        at uk.ac.ebi.interpro.scan.jms.activemq.NonZeroExitOnUnrecoverableError.failed(NonZeroExitOnUnrecoverableError.java:43)
        at uk.ac.ebi.interpro.scan.jms.master.StandaloneBlackBoxMaster.run(StandaloneBlackBoxMaster.java:157)
        at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:475)
InterProScan analysis failed. Exception thrown by StandaloneBlackBoxMaster. Check the log file for details

**Comment by gsn7** [comment] 2021-01-13 16:11
i am surprised that you are getting such errors consistently when running against a small number of input sequences like 5,000. usually, this error is caused by a temporary file system problem, such that re-running your analysis is expected to work.

what is your linux distribution and the file system? I would like like to reproduce this and if you can, send us the set of input sequences that consistently fail (you can send a zipped file to interhelp@ebi.ac.uk if privacy is required).

**Comment by minhasbushra** [comment] 2021-01-13 17:01
Thanks I just e mailed you the files.

**Comment by gsn7** [comment] 2021-01-15 12:47
i have run your input successfully on two different linux systems; ubuntu 20.04 and redhat 7.4. we don't expect a small input set of 5k sequences to generate the error you have. 
the error is occurring at the point where InterProScan is preparing and writing output results to disk and at this time it is I/O intensive. 
what is your linux distribution and what is the file system? 
you can check if the filesystem may have something to do with this error by setting the temp directory (-T) to /tmp

**Comment by minhasbushra** [comment] 2021-01-15 18:43
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

Filesystem                             Type      Size  Used Avail Use% Mounted on
devtmpfs                               devtmpfs   63G     0   63G   0% /dev
tmpfs                                  tmpfs      63G  488K   63G   1% /dev/shm
tmpfs                                  tmpfs      63G  2.3G   61G   4% /run
rootfs                                 tmpfs      63G  3.2G   60G   5% /
rw                                     tmpfs      63G  4.0K   63G   1% /.sllocal/log
tmpfs                                  tmpfs      63G     0   63G   0% /sys/fs/cgroup
tmpfs                                  tmpfs      10M     0   10M   0% /var/tmp
/dev/sda2                              ext4      106G  1.6G   99G   2% /scratch.local
/dev/sda3                              ext4      154G   61M  146G   1% /torque
iccp                                   gpfs      2.4P  1.1P  1.3P  46% /gpfs/iccp
condo-nfs.ncsa.illinois.edu:/terradata nfs       3.0P  2.7P  254T  92% /terradata
tmpfs                                  tmpfs     300M   94M  207M  32% /var/lib/sss/db

It ran successfully one time with 5000 sequences, but failed the rest of the times. I am not sure why it ran then if there is a problem with the file system. I am trying it with /tmp option, will update soon. 

Thanks for the help. 
Bushra

**Comment by minhasbushra** [comment] 2021-01-18 17:17
Here is the response from my system administrator regarding file locking and temp directory 
"The campus cluster file system supports full POSIX file locking (it is an IBM Spectrum Scale file system).  
"

**Comment by gsn7** [comment] 2021-03-19 16:36
this bug is now fixed. the patch as described in Issue 1 at https://interproscan-docs.readthedocs.io/en/latest/KnownIssues.html#error-after-more-than-90-completed should fix this problem now.

**Comment by gsn7** [comment] 2021-04-15 09:18
this bug is now fixed in InterProScan-5.51-85.0

**Closed by gsn7** 2021-04-15 09:18 UTC
